openapi: 3.0.3
info:
  title: Swagger Users - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: produtoServico
    description: Controle de Produto/Serviço
paths:
  /produtoServico:
    post:
      tags: 
      - produtoServico
      summary: Cadastro de Produto/Serviço.
      operationId: createProdutoServico
      requestBody:
        description: Objeto de cadastro de Produto/Serviço
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroProdutoServicoDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/CadastroProdutoServicoDTO'
      responses:
        201:
          description: Cadastro realizado com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoServicoDTO'
    get:
      tags: 
      - produtoServico
      summary: Lista todos os Produto/Serviço.
      operationId: listProdutoServico
      responses:
        200:
          description: Listagem realiza com sucesso!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProdutoServicoDTO'
  /produtoServico/{id}:
    get:
      tags:
        - produtoServico
      summary: Busca um Produto/Serviço através do UUID.
      operationId: readProdutoServico
      parameters:
        - name: id
          in: path
          example: e6bf2e78-b72c-494e-a8b2-eebc35b8dcbe
          description: 'ID do Produto/Serviço'
          required: true
          schema:
            type: string
      responses:
        200:
          description: Busca realizada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoServicoDTO'
    put:
      tags:
        - produtoServico
      summary: Atualiza um Produto/Serviço através do UUID.
      operationId: updateProdutoServico
      requestBody:
        description: Objeto de atualização de Produto/Serviço
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroProdutoServicoDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/CadastroProdutoServicoDTO'
      parameters:
        - name: id
          in: path
          example: e6bf2e78-b72c-494e-a8b2-eebc35b8dcbe
          description: 'ID do Produto/Serviço'
          required: true
          schema:
            type: string
      responses:
        200:
          description: Atualização realizada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoServicoDTO'
    delete:
      tags:
        - produtoServico
      summary: Exclui um Produto/Serviço através do UUID.
      operationId: deleteProdutoServico
      parameters:
        - name: id
          in: path
          example: e6bf2e78-b72c-494e-a8b2-eebc35b8dcbe
          description: 'ID do Produto/Serviço'
          required: true
          schema:
            type: string
      responses:
        204:
          description: Exclusão realizada com sucesso!
components:
  schemas:
    CadastroProdutoServicoDTO:
      type: object
      required: 
      - descricao
      - tipo
      properties:
        descricao:
          type: string
          example: Descrição Exemplo
        tipo:
          type: integer
          description: 1 - Produto; 2 - Serviço;
          example: 1
    ProdutoServicoDTO:
      type: object
      properties:
        id:
          type: string
          example: e6bf2e78-b72c-494e-a8b2-eebc35b8dcbe
        descricao:
          type: string
          example: Descrição Exemplo
        tipo:
          type: integer
          description: 1 - Produto; 2 - Serviço;
          example: 1